name: Update Blog Content on Dispatch

on:
  repository_dispatch:
    types: [update-blog]  # This should match the dispatch type sent from the Obsidian repo

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest  # Or any other runner you prefer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify your project's Node.js version

    - name: Deploy to Vercel
      run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --projectId ${{ secrets.VERCEL_PROJECT_ID }}
      env:
        CI: true  # Ensures that Vercel runs in CI-mode

    - name: Cleanup if needed
      run: echo "Cleanup tasks"

