name: Update Blog Content on Dispatch

on:
  repository_dispatch:
    types: [update-blog]  # This should match the dispatch type sent from the Obsidian repo

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest  # Or any other runner you prefer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify your project's Node.js version

    - name: Deploy to Vercel
      run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        CI: true  # Ensures that Vercel runs in CI-mode

    - name: Cleanup if needed
      run: echo "Cleanup tasks"

  notify-new-post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Astro Blog repo
      uses: actions/checkout@v2
      with:
        path: 'astro-blog'
    
    - name: Checkout Obsidian repo
      uses: actions/checkout@v2
      with:
        repository: 'obsidian'
        path: 'obsidian'

    - name: Run script
      run: node astro-blog/.github/scripts/checkAndSendEmails.js
      env:
        CONTENT_DIR: ${{ github.workspace }}/obsidian/Blog/posts
    
